### ISSUE TITLE
GO modules

### ISSUE THREAD

**Issue by alexmatsak** [furdarius/rabbitroutine#10]
Hello! Any future plans for adding [module support](https://github.com/golang/go/wiki/Modules#gomod) ?

**Comment by furdarius** [comment]
Hello! Yep, it could be a good idea :)

I've released `v0.6.0` with go modules and upgraded dependencies: https://github.com/furdarius/rabbitroutine/releases/tag/v0.6.0

Thank you for the issue and feel free to give any feedback.
