### ISSUE TITLE
question: gracefull shutdown for consumer

### ISSUE THREAD

**Issue by ergoz** [furdarius/rabbitroutine#19]
i checked examples, test files, etc. but not found how to correctly make a gracefull shutdown.

how i see it should be (may be i am wrong):

1) stop receiving new tasks in channel
2) wait to processing tasks finished
3) close channel
4) close connection

could you provide an example to do it in right way?

**Comment by furdarius** [comment]
Hi @ergoz,

Actually, the consumer example in the repo has been implemented with a graceful shutdown in mind. To initiate the shutdown process, `context.Context` is used. 

The `Consumer` interface has the `Consume` method,  which accepts `context.Context` as the first parameter:

https://github.com/furdarius/rabbitroutine/blob/0bcf8b9a2288730dddac1abee2f35b56c7d8dbfa/consumer.go#L16

When the context is cancelled/closed, we stop the processing of the incoming messages:
https://github.com/furdarius/rabbitroutine/blob/0bcf8b9a2288730dddac1abee2f35b56c7d8dbfa/examples/consume/consumer.go#L109

So, the only thing left is to initiate the process of the shutdown. Common practice is to receive a signal from an external service. As an example, in the case of Kubernetes pod, the application receives `SIGTERM` as the signal (https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/), so we could rely on it as the way to kick-off the shutdown process. That's exactly what is happening in the consumer example:
https://github.com/furdarius/rabbitroutine/blob/0bcf8b9a2288730dddac1abee2f35b56c7d8dbfa/examples/consume/main.go#L67

The `golang.org/x/sync/errgroup` package helps to automate the context cancellation. The ctx returned from the `errgroup.WithContext` will be closed in case of an error happened in one of the `g.Go` callbacks.

https://github.com/furdarius/rabbitroutine/blob/0bcf8b9a2288730dddac1abee2f35b56c7d8dbfa/examples/consume/main.go#L22

Hope that helps. Let me know in case of questions left.

**Comment by ergoz** [comment]
@furdarius thanks for detailed answer! I will try it!

**Comment by rishabh2898** [comment]
> @furdarius thanks for detailed answer! I will try it!

@ergoz @furdarius  I'm still facing issues in on demand graceful shutdown , can you please help me with it.
