### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sumorf** [furdarius/rabbitroutine#7]
Build like this:

SET CGO_ENABLED=0
SET GOOS=windows
SET GOARCH=386
go build

Got an error.
.\connector.go:45:25: constant 9223372036854775807 overflows uint.\connector.go:45:25: constant 9223372036854775807 overflows uint

it should be like this in line 45: 
cfg.ReconnectAttempts = math.MaxUint32

**Comment by furdarius** [comment]
Wow, really, didn't tested library on windows and for 32bit systems. Thank your for issue!
Have no laptop around me now, so I'll fix it on the next week.
